### ISSUE TITLE
Muriki weather does not respect shadekin phasing

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#84] opened 2024-01-08 03:26 UTC
#### Brief description of the bug
Shadekin phasing is not respected by muriki weather, and lose health/die in the rain.

#### What you expected to happen
Phased shadekin are technically reality-jumping and should not be affected by adverse weather conditions.

#### What actually happened
Shadekin melt while outside and phased.

#### Steps to reproduce
- Be shadekin
- Phase
- Go outside
- Scream in pain as your body melts

**Comment by Willburd** [comment] 2024-01-08 10:51
Cannot reproduce, and code already runs an "is_incorporeal" check. I did catch maglev rails not respecting it though.

**Comment by Willburd** [comment] 2024-01-13 17:53
Cannot reproduce, closing until revalidated?

**Closed as completed by Willburd** 2024-01-13 17:53 UTC
Labels: bug, Cannot Reproduce
